### ISSUE TITLE
关于打卡中的位置问题

### ISSUE THREAD

**Issue by LineBrown** [ruizhi11/SEU-Daily-Report#1]
作者您好，首先很感谢你的脚本。在实际运行中，发现脚本跑上去的填报中，当前位置这一项的信息是空的。然后发现post上去的信息中，有'DZ_DQWZ_JD': '31.88'和'DZ_DQWZ_WD': '118.80'，这两个是地址信息（经度和纬度），但是实际的信息是经度是118，纬度要是31，post上去的信息经纬度是反了的。不知道这是写填报程序的人本身分不清经纬度 还是 故意而为之的？

**Comment by ruizhi11** [comment]
您好，脚本中个人信息的填报大部分是通过爬虫直接从前一天的信息中获取的，经过查看之前手动填报记录的打卡信息，我认为经度和纬度弄反大概率是写程序的人并不清楚经纬度的概念。至于运行中位置是空但有经纬度的状况，这个我在手动填报时也出现过这样的状况，但在过程中我发现可能有前一天打卡中有位置信息但使用脚本确无法正确提交的状况，会尝试修复这个bug。

**Comment by LineBrown** [comment]
好的，我现在就是直接往'DZ_DQWZ_JD'传入纬度值，往这个里'DZ_DQWZ_WD'传入经度值。
