### ISSUE TITLE
为什么打卡经常会覆盖昨天的数据？

### ISSUE THREAD

**Issue by Mathisdifficult** [ruizhi11/SEU-Daily-Report#2]
请问作者出现过这种情况吗？就是自动打卡提交后，前一天的打卡数据会被覆盖 系统里面查不到前一天的打卡数据了。

**Comment by Mathisdifficult** [comment]
CZRQ表示的是什么意思？我debug的时候 发现CZRQ是昨天的日期即'CZRQ': '2021-01-22 07'

**Comment by ruizhi11** [comment]
你可以使用Chrome或者Firefox在网页端打卡用F12看看传的数据。我个人很久没用这个脚本了...所以也没有维护。你修改代码之后可以提pull request，我测试一下然后merge

**Comment by Mathisdifficult** [comment]
> 你可以使用Chrome或者Firefox在网页端打卡用F12看看传的数据。我个人很久没用这个脚本了...所以也没有维护。你修改代码之后可以提pull request，我测试一下然后merge

好的
