### ISSUE TITLE
当前位置的post_key改正

### ISSUE THREAD

**Issue by InTereSTingHE** [ruizhi11/SEU-Daily-Report#3]
代码里当前位置的key值是'DZ_DQMZ'，不知道是作者当时将错就错（毕竟学校程序员连经纬度都能弄反）还是笔误，总之现在应该是'DZ_DQWZ'。

![屏幕截图 2021-03-08 173425](https://user-images.githubusercontent.com/32561116/110302817-9e742a80-8034-11eb-969d-31be44c12e7a.png)

**Comment by InTereSTingHE** [comment]
可能是这个问题导致了#1 的当前位置为空

**Comment by ruizhi11** [comment]
已merge
